is_train: True 
out_root_path: /outputs/audio2pose/ 
train_data_path: /data/beat_cache/beat_4english_15_141/train/ 
val_data_path: /data/beat_cache/beat_4english_15_141/val/ 
test_data_path: /data/beat_cache/beat_4english_15_141/test/ 
mean_pose_path: /data/beat_cache/beat_4english_15_141/train/
std_pose_path: /data/beat_cache/beat_4english_15_141/train/
test_ckpt: /data/beat_cache/beat_4english_15_141/weights/pae.bin
torch_hub_path: /data/checkpoints/ 
dataset: beat
new_cache: False
pose_rep: bvh_rot
pose_world: worldpos
audio_rep: wave16k
audio_mfcc: mfcc
facial_rep: facial52
word_rep: text
emo_rep: emo
sem_rep: sem
speaker_id: False
audio_norm: True
facial_norm: True
pose_dims: 219
batch_size: 256
test_period: 10
pose_length: 34
window: 2
embedding_channels: 10
stride: 3
vae_length: 300
hidden_size: 128
g_name: PaeModel 
model: motion_pae
trainer: pae
variational_encoding: False
rec_weight: 1
vel_weight: 0.1
kld_weight: 0
lr_base: 0.00012 
grad_norm: 0
epochs: 140